name: NyaaCore
main: cat.nyaa.nyaacore.NyaaCoreLoader
description: "Code infrastructure for all NyaaCat plugins."
version: ${version}
softdepend: [ Essentials ]
authors: [ RecursiveG,Librazy,cyilin ]
website: "https://github.com/NyaaCat/NyaaCore"
api-version: 1.18
libraries:
  - 'org.cadixdev:lorenz:0.5.8'
